channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - tensorflow=2.8.0
  - biopython=1.79
  - parasail-python=1.3.3
  - boost=1.80.0
  - boost-cpp=1.80.0
  - numpy=1.24.2
  - pandas==1.3.5
  - mmseqs2=14.7e284
  - pip=23.0.1
  - pysam=0.21.0
  - pytest=7.2.2
  - python=3.9
  - cmake=3.22.1
