channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - numpy>=1.19
  - biotite
  - mmseqs2==15.6f452
  - pip
  - python==3.11
  - libdeflate
  - pip:
    - pysam==0.21.0
    - pyopal>=0.5
    - foldcomp
    - tqdm
    # onnx stuff
    - onnxruntime-gpu
    # mDeepFRI
    - mdeepfri
