channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - numpy>=1.19
  - mmseqs2=14.7e284
  - pip
  - pysam>=0.16.0
  - pytest
  - python
  - onnxruntime>=1.10
  - pip:
    - pyopal
