channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - numpy>=1.19
  - scipy
  - biopython
  - mmseqs2=14.7e284
  - pip
  - pytest
  - python>=3.11
  - onnxruntime>=1.10
  - onnxruntime-gpu
  - pip:
    - pyopal
    - pysam>=0.21.0
    - foldcomp
