channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - numpy>=1.19
  - scipy
  - biopython
  - mmseqs2=14.7e284
  - pip
  - pytest
  - python>=3.11
  - libdeflate
  - pip:
    - pyopal
    - pysam>=0.21.0
    - foldcomp
    - onnxruntime-gpu
    - torch
    - pre-commit
