channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - parasail-python=1.3.3
  - click
  - boost>=1.80.0
  - boost-cpp>=1.80.0
  - numpy>=1.19
  - pandas>=1.2
  - mmseqs2=14.7e284
  - pip
  - pysam>=0.16.0
  - pytest
  - python
  - cmake>=3.19
  - onnxruntime>=1.10
