channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - numpy>=1.19
  - biopython
  - mmseqs2=14.7e284
  - pip
  - python==3.11
  - libdeflate
  - pip:
    - pysam==0.21.0
    - pyopal>=0.5
    - foldcomp
    # onnx stuff
    - onnxruntime-gpu
